name: ${project.name}
main: com.michaelelin.WGDropFlag.WGDropFlagPlugin
version: ${project.version}
description: ${project.description}
website: ${project.url}
database: false
depend: [WorldGuard, WorldEdit, WGCustomFlags]
authors: [Dumbo52]
